---
- name: Clone QCOW2 Image and Create a VM
  hosts: localhost
  become: yes
  vars_prompt:
    - name: "vm_name"
      prompt: "Enter the VM name"
      default: "test-vm"
      private: no

    - name: "vm_ram"
      prompt: "Enter the amount of RAM for the VM (in MB)"
      default: 2048
      private: no

    - name: "vm_cpu"
      prompt: "Enter the number of CPUs for the VM"
      default: 2
      private: no

    - name: "base_qcow_image"
      prompt: "Enter the path to the base QCOW2 image"
      default: "/var/lib/libvirt/images/ubuntu24-Main.qcow2"
      private: no

  vars:
    # Define new_qcow_image using the user-defined vm_name
    new_qcow_image: "/var/lib/libvirt/images/{{ vm_name }}.qcow2"

  tasks:
    - name: Ensure images directory exists
      file:
        path: /var/lib/libvirt/images
        state: directory
        mode: '0755'

    - name: Clone the QCOW2 image
      shell: sudo qemu-img convert -O qcow2 {{ base_qcow_image }} {{ new_qcow_image }}
      args:
        creates: "{{ new_qcow_image }}"

    - name: Generate a random MAC address
      shell: "echo 52:54:00:$(openssl rand -hex 3 | sed 's/\\(..\\)/\\1:/g; s/:$//')"
      register: mac_address

    - name: Display generated MAC address
      debug:
        msg: "Generated MAC Address: {{ mac_address.stdout }}"

    - name: Ensure VM does not already exist
      command: virsh list --all
      register: existing_vms

    - name: Create VM if it does not exist
      shell: |
        virt-install \
        --name {{ vm_name }} \
        --ram {{ vm_ram }} \
        --vcpus {{ vm_cpu }} \
        --disk path={{ new_qcow_image }},format=qcow2 \
        --os-variant ubuntu20.04 \
        --network bridge=virbr0,mac={{ mac_address.stdout }},model=virtio \
        --import \
        --graphics vnc \
        --noautoconsole
      when: vm_name not in existing_vms.stdout

    - name: Print status
      debug:
        msg: "VM {{ vm_name }} created successfully with MAC Address: {{ mac_address.stdout }}"
