---
- name: Clone QCOW2 Image and Create VM
  hosts: localhost
  become: yes
  connection: local
  tasks:

    - name: Ensure images directory exists
      file:
        path: /var/lib/libvirt/images
        state: directory
        mode: '0755'

    - name: Clone the QCOW2 image using qemu-img
      shell: sudo qemu-img convert -O qcow2 /var/lib/libvirt/images/ubuntu24-Main.qcow2 /var/lib/libvirt/images/ubuntu24-Main-copy.qcow2
      args:
        creates: /var/lib/libvirt/images/ubuntu24-Main-copy.qcow2

    - name: Generate a random MAC address
      shell: "echo 52:54:00:$(openssl rand -hex 3 | sed 's/\\(..\\)/\\1:/g; s/:$//')"
      register: mac_address

    - name: Display generated MAC address
      debug:
        msg: "Generated MAC Address: {{ mac_address.stdout }}"

    - name: Install the virtual machine
      command: >
        sudo virt-install --name ubuntu24-Main-copy --ram 1024 --vcpus 1
        --disk path=/var/lib/libvirt/images/ubuntu24-Main-copy.qcow2
        --import --network bridge=virbr0,mac={{ mac_address.stdout }}
        --graphics vnc,listen=0.0.0.0 --noautoconsole
        --os-variant ubuntu22.04

