---
- name: Create a VM on KVM
  hosts: localhost
  become: yes
  vars:
    vm_name: "{{ lookup('env', 'VM_NAME') | default('test-vm', true) }}"  # Default to 'test-vm' if VM_NAME is not set
    vm_ram: "{{ lookup('env', 'VM_RAM') | default(2048, true) }}"  # Default to 2048MB if VM_RAM is not set
    vm_cpu: "{{ lookup('env', 'VM_CPU') | default(2, true) }}"  # Default to 2 CPUs if VM_CPU is not set

  tasks:
    - name: Ensure VM does not already exist
      command: virsh list --all
      register: existing_vms

    - name: Create VM if it does not exist
      shell: |
        virt-install \
        --name {{ vm_name }} \
        --ram {{ vm_ram }} \
        --vcpus {{ vm_cpu }} \
        --disk path=/var/lib/libvirt/images/{{ vm_name }}.qcow2,format=qcow2 \
        --os-variant ubuntu20.04 \
        --network bridge=virbr0,model=virtio \
        --import \
        --graphics vnc \
        --noautoconsole
      when: vm_name not in existing_vms.stdout

    - name: Print status
      debug:
        msg: "VM {{ vm_name }} created successfully!"
